package Giocare;

import Allenamento.ProgrammaRobot;
import Allenamento.SchedaIstruzione;
import java.awt.datatransfer.DataFlavor;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JComponent;
import javax.swing.TransferHandler;
import robogp.matchmanager.RobotMarker;

/**
 *
 * @author Sorrentino Vair
 */
public class FinestraDiProgrammazione extends javax.swing.JFrame {
    private RobotMarker robot;
    private List<SchedaIstruzione> pool;
    private ProgrammaRobot pr;
    private Map<SchedaIstruzione,CustomLabelScheda> init_pos_scheda;
    
    /**
     * Creates new form FinestraDiProgrammazione
     */
    public FinestraDiProgrammazione(RobotMarker robot) {
        initComponents();
        label_icona_robot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/"+robot.getName()+".png"))); // NOI18N
        init_pos_scheda = new HashMap<>();
        this.robot = robot;
        this.pool = null;
        this.pr = new ProgrammaRobot();
        init_reg();
        this.setTitle("Finestra di programmazione di "+robot.getName());
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
    }
    
    public void setPool(List<SchedaIstruzione> pool){
        this.pool = pool;
        loadSchede();
    }
    
    public ProgrammaRobot getProgram(){
        pr.resetProg();
        pr.addScheda(reg1.getScheda());
        pr.addScheda(reg2.getScheda());
        pr.addScheda(reg3.getScheda());
        pr.addScheda(reg4.getScheda());
        pr.addScheda(reg5.getScheda());
        return pr;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pannello_principale = new javax.swing.JPanel();
        panel_registri = new javax.swing.JPanel();
        reg1 = new Giocare.CustomLabelScheda();
        reg2 = new Giocare.CustomLabelScheda();
        reg3 = new Giocare.CustomLabelScheda();
        reg4 = new Giocare.CustomLabelScheda();
        reg5 = new Giocare.CustomLabelScheda();
        label_reg_scritta = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        customLabelScheda4 = new Giocare.CustomLabelScheda();
        customLabelScheda7 = new Giocare.CustomLabelScheda();
        customLabelScheda8 = new Giocare.CustomLabelScheda();
        pannello_ok = new javax.swing.JPanel();
        button_ok = new javax.swing.JButton();
        label_icona_robot = new javax.swing.JLabel();
        customLabelScheda0 = new Giocare.CustomLabelScheda();
        customLabelScheda1 = new Giocare.CustomLabelScheda();
        customLabelScheda6 = new Giocare.CustomLabelScheda();
        customLabelScheda2 = new Giocare.CustomLabelScheda();
        customLabelScheda5 = new Giocare.CustomLabelScheda();
        customLabelScheda3 = new Giocare.CustomLabelScheda();
        label_pool_scritta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        pannello_principale.setBackground(new java.awt.Color(255, 255, 255));

        panel_registri.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        label_reg_scritta.setText("Registri da programmare");
        label_reg_scritta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout panel_registriLayout = new javax.swing.GroupLayout(panel_registri);
        panel_registri.setLayout(panel_registriLayout);
        panel_registriLayout.setHorizontalGroup(
            panel_registriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_registriLayout.createSequentialGroup()
                .addGroup(panel_registriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_registriLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(reg1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(reg2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(reg3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(reg4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(reg5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_registriLayout.createSequentialGroup()
                        .addGap(290, 290, 290)
                        .addComponent(label_reg_scritta)))
                .addGap(41, 41, 41))
        );
        panel_registriLayout.setVerticalGroup(
            panel_registriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_registriLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_reg_scritta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_registriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(reg3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_registriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(reg4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(reg5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(panel_registriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(reg2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(reg1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        pannello_ok.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        button_ok.setText("OK");
        button_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_okActionPerformed(evt);
            }
        });

        label_icona_robot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/robot-red.png"))); // NOI18N

        javax.swing.GroupLayout pannello_okLayout = new javax.swing.GroupLayout(pannello_ok);
        pannello_ok.setLayout(pannello_okLayout);
        pannello_okLayout.setHorizontalGroup(
            pannello_okLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pannello_okLayout.createSequentialGroup()
                .addGroup(pannello_okLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pannello_okLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(label_icona_robot))
                    .addGroup(pannello_okLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(button_ok, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        pannello_okLayout.setVerticalGroup(
            pannello_okLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pannello_okLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_icona_robot)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button_ok, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        label_pool_scritta.setText("Pool personale di schede");
        label_pool_scritta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(customLabelScheda2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(customLabelScheda3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(customLabelScheda6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(customLabelScheda5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(customLabelScheda8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(customLabelScheda1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(customLabelScheda7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(customLabelScheda0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pannello_ok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(customLabelScheda4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(291, 291, 291)
                        .addComponent(label_pool_scritta)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_pool_scritta)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(customLabelScheda6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customLabelScheda8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customLabelScheda7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customLabelScheda2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customLabelScheda4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(customLabelScheda3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pannello_ok, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(customLabelScheda1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(customLabelScheda5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(customLabelScheda0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pannello_principaleLayout = new javax.swing.GroupLayout(pannello_principale);
        pannello_principale.setLayout(pannello_principaleLayout);
        pannello_principaleLayout.setHorizontalGroup(
            pannello_principaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_registri, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pannello_principaleLayout.setVerticalGroup(
            pannello_principaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pannello_principaleLayout.createSequentialGroup()
                .addComponent(panel_registri, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(36, 36, 36)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pannello_principale, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pannello_principale, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_okActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_button_okActionPerformed
   
    private void loadSchede(){
        SchedaIstruzione temp;
                
        temp = pool.get(0);
        customLabelScheda0.setScheda(temp);
        customLabelScheda0.addMouseListener(new DragMouseAdapter());
        customLabelScheda0.setTransferHandler(new NoImportTransferHandler());
        init_pos_scheda.put(temp,customLabelScheda0);
        
        temp = pool.get(1);
        customLabelScheda1.setScheda(temp);
        customLabelScheda1.addMouseListener(new DragMouseAdapter());
        customLabelScheda1.setTransferHandler(new NoImportTransferHandler());
        init_pos_scheda.put(temp,customLabelScheda1);
        
        temp = pool.get(2);
        customLabelScheda2.setScheda(temp);
        customLabelScheda2.addMouseListener(new DragMouseAdapter());
        customLabelScheda2.setTransferHandler(new NoImportTransferHandler());
        init_pos_scheda.put(temp,customLabelScheda2);
        
        temp = pool.get(3);
        customLabelScheda3.setScheda(temp);
        customLabelScheda3.addMouseListener(new DragMouseAdapter());
        customLabelScheda3.setTransferHandler(new NoImportTransferHandler());
        init_pos_scheda.put(temp,customLabelScheda3);
        
        temp = pool.get(4);
        customLabelScheda4.addMouseListener(new DragMouseAdapter());
        customLabelScheda4.setScheda(temp);
        customLabelScheda4.setTransferHandler(new NoImportTransferHandler());
        init_pos_scheda.put(temp,customLabelScheda4);
        
        temp = pool.get(5);
        customLabelScheda5.addMouseListener(new DragMouseAdapter());
        customLabelScheda5.setScheda(temp);
        customLabelScheda5.setTransferHandler(new NoImportTransferHandler());
        init_pos_scheda.put(temp,customLabelScheda5);
        
        temp = pool.get(6);
        customLabelScheda6.addMouseListener(new DragMouseAdapter());
        customLabelScheda6.setScheda(temp);
        customLabelScheda6.setTransferHandler(new NoImportTransferHandler());
        init_pos_scheda.put(temp,customLabelScheda6);
        
        temp = pool.get(7);
        customLabelScheda7.addMouseListener(new DragMouseAdapter());
        customLabelScheda7.setScheda(temp);
        customLabelScheda7.setTransferHandler(new NoImportTransferHandler());
        init_pos_scheda.put(temp,customLabelScheda7);
        
        temp = pool.get(8);
        customLabelScheda8.addMouseListener(new DragMouseAdapter());
        customLabelScheda8.setScheda(temp);
        customLabelScheda8.setTransferHandler(new NoImportTransferHandler());
        init_pos_scheda.put(temp,customLabelScheda8);

    }
    
    //Evento per l' eliminazione della scheda nel registro
    private MouseAdapter ma = new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                if (evt.getClickCount() == 2 && evt.getSource() instanceof CustomLabelScheda ) {
                    if ( ((CustomLabelScheda)evt.getSource()).isSet() ){
                        SchedaIstruzione temp;
                        temp = ((CustomLabelScheda)evt.getSource()).getScheda();
                        init_pos_scheda.get(temp).setScheda(temp);
                    }
                }
            }
    };
    
    //gestore di eventi per drag&drop che permette il trascinamento del mouse
    class DragMouseAdapter extends MouseAdapter {
        public void mousePressed(MouseEvent e) {
            JComponent c = (JComponent) e.getSource();
            if (c.getTransferHandler() != null){
                TransferHandler handler = c.getTransferHandler();
                handler.exportAsDrag(c, e, TransferHandler.COPY);
            } 
        }
    }
    
    //gestore di eventi per drag&drop su cui non si puo fare il drop
    public class NoImportTransferHandler extends TransferHandler {
        NoImportTransferHandler(){
            super("scheda");
        }
        public boolean canImport(JComponent comp, DataFlavor[] transferFlavors){
            return false;
        }
        public boolean canImport(TransferHandler.TransferSupport support){
            return false;
        }
    }
    
    //TranferHandler per i registri: evita di mettere più schede sullo stesso registro
    public class regTransferHandler extends TransferHandler {       
        regTransferHandler(){
            super("scheda");
        }
        
        public boolean canImport(JComponent comp, DataFlavor[] transferFlavors){
            if (((CustomLabelScheda)comp).isSet()){
                return false;
            }    
            return true;
        }      
    }
    
    public void init_reg(){
        reg1.addMouseListener(ma);
        reg1.setTransferHandler(new regTransferHandler()); //setto glie venti per il drag&drop
        
        reg2.addMouseListener(ma);
        reg2.setTransferHandler(new regTransferHandler());
        
        reg3.addMouseListener(ma);
        reg3.setTransferHandler(new regTransferHandler());
        
        reg4.addMouseListener(ma);
        reg4.setTransferHandler(new regTransferHandler());
        
        reg5.addMouseListener(ma);  
        reg5.setTransferHandler(new regTransferHandler());
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_ok;
    private Giocare.CustomLabelScheda customLabelScheda0;
    private Giocare.CustomLabelScheda customLabelScheda1;
    private Giocare.CustomLabelScheda customLabelScheda2;
    private Giocare.CustomLabelScheda customLabelScheda3;
    private Giocare.CustomLabelScheda customLabelScheda4;
    private Giocare.CustomLabelScheda customLabelScheda5;
    private Giocare.CustomLabelScheda customLabelScheda6;
    private Giocare.CustomLabelScheda customLabelScheda7;
    private Giocare.CustomLabelScheda customLabelScheda8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel label_icona_robot;
    private javax.swing.JLabel label_pool_scritta;
    private javax.swing.JLabel label_reg_scritta;
    private javax.swing.JPanel panel_registri;
    private javax.swing.JPanel pannello_ok;
    private javax.swing.JPanel pannello_principale;
    private Giocare.CustomLabelScheda reg1;
    private Giocare.CustomLabelScheda reg2;
    private Giocare.CustomLabelScheda reg3;
    private Giocare.CustomLabelScheda reg4;
    private Giocare.CustomLabelScheda reg5;
    // End of variables declaration//GEN-END:variables
}
