package Allenamento;

import java.awt.Color;
import java.io.File;
import javax.swing.BorderFactory;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import robogp.matchmanager.RobotMarker;

/**
 *
 * @author Sorrentino Vair
 */
public class setting_allenamento extends javax.swing.JFrame {
    
    String robodrome;
    int dock;
    String robot;
    JLabel selected;
    /**
     * Creates new form setting_allenamento
     */
    public setting_allenamento() {
        initComponents();
        initRobodromeSelector();
        initDockSelector();
        dock = 1;
        robodrome = "checkmate";
        selected = null;
    }
    
    private void initDockSelector(){
        String[] opts = new String[8];
        Integer indice = 1;
        for (int i = 0; i < 8; i++){
            opts[i] = indice.toString();
            indice++;
        }
        this.select_docks.setModel(new DefaultComboBoxModel<>(opts));
    }
    
    private void initRobodromeSelector() {
        File robodromeDir = new File("robodromes");
        File[] robodromeFiles = robodromeDir.listFiles();
        String[] opts = new String[robodromeFiles.length];
        for (int i = 0; i < opts.length; i++) {
            opts[i] = robodromeFiles[i].getName().split("\\.")[0];
        }
        this.select_robodromes.setModel(new DefaultComboBoxModel<>(opts));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pannello_principale = new javax.swing.JPanel();
        select_robodromes = new javax.swing.JComboBox<>();
        pannello_robots = new javax.swing.JPanel();
        robot_blu = new javax.swing.JLabel();
        robot_turquoise = new javax.swing.JLabel();
        robot_emerald = new javax.swing.JLabel();
        robot_orange = new javax.swing.JLabel();
        robot_violet = new javax.swing.JLabel();
        robot_red = new javax.swing.JLabel();
        robot_yellow = new javax.swing.JLabel();
        robot_green = new javax.swing.JLabel();
        select_docks = new javax.swing.JComboBox<>();
        avvia_allenamento = new javax.swing.JButton();
        label_robodromo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        button_home = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pannello_principale.setPreferredSize(new java.awt.Dimension(500, 400));

        select_robodromes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        select_robodromes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                select_robodromesActionPerformed(evt);
            }
        });

        pannello_robots.setBackground(new java.awt.Color(255, 255, 255));

        robot_blu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/robot-blue.png"))); // NOI18N
        robot_blu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        robot_blu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                robot_bluMouseClicked(evt);
            }
        });

        robot_turquoise.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/robot-turquoise.png"))); // NOI18N
        robot_turquoise.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        robot_turquoise.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                robot_turquoiseMouseClicked(evt);
            }
        });

        robot_emerald.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/robot-green.png"))); // NOI18N
        robot_emerald.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        robot_emerald.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                robot_emeraldMouseClicked(evt);
            }
        });

        robot_orange.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/robot-orange.png"))); // NOI18N
        robot_orange.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        robot_orange.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                robot_orangeMouseClicked(evt);
            }
        });

        robot_violet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/robot-violet.png"))); // NOI18N
        robot_violet.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        robot_violet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                robot_violetMouseClicked(evt);
            }
        });

        robot_red.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/robot-red.png"))); // NOI18N
        robot_red.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        robot_red.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                robot_redMouseClicked(evt);
            }
        });

        robot_yellow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/robot-yellow.png"))); // NOI18N
        robot_yellow.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        robot_yellow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                robot_yellowMouseClicked(evt);
            }
        });

        robot_green.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/robot-emerald.png"))); // NOI18N
        robot_green.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        robot_green.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                robot_greenMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pannello_robotsLayout = new javax.swing.GroupLayout(pannello_robots);
        pannello_robots.setLayout(pannello_robotsLayout);
        pannello_robotsLayout.setHorizontalGroup(
            pannello_robotsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pannello_robotsLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(pannello_robotsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(robot_green, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(robot_blu, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(pannello_robotsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(robot_turquoise, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(robot_emerald, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(51, 51, 51)
                .addGroup(pannello_robotsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(robot_violet, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(robot_red, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(pannello_robotsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(robot_orange, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(robot_yellow, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        pannello_robotsLayout.setVerticalGroup(
            pannello_robotsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pannello_robotsLayout.createSequentialGroup()
                .addGap(25, 25, Short.MAX_VALUE)
                .addGroup(pannello_robotsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pannello_robotsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(robot_turquoise, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(robot_violet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(robot_orange, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(robot_blu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(pannello_robotsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(robot_green, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(robot_emerald, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(robot_red, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(robot_yellow, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        select_docks.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        select_docks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                select_docksActionPerformed(evt);
            }
        });

        avvia_allenamento.setText("Avvia Allenamento");
        avvia_allenamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avvia_allenamentoActionPerformed(evt);
            }
        });

        label_robodromo.setText("Robodromo");

        jLabel1.setText("Dock di partenza");

        button_home.setText("Menu Principale");
        button_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_homeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pannello_principaleLayout = new javax.swing.GroupLayout(pannello_principale);
        pannello_principale.setLayout(pannello_principaleLayout);
        pannello_principaleLayout.setHorizontalGroup(
            pannello_principaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pannello_principaleLayout.createSequentialGroup()
                .addGroup(pannello_principaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pannello_principaleLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(pannello_robots, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pannello_principaleLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(pannello_principaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pannello_principaleLayout.createSequentialGroup()
                                .addComponent(button_home)
                                .addGap(67, 67, 67)
                                .addComponent(avvia_allenamento, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pannello_principaleLayout.createSequentialGroup()
                                .addComponent(label_robodromo)
                                .addGap(18, 18, 18)
                                .addComponent(select_robodromes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(select_docks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        pannello_principaleLayout.setVerticalGroup(
            pannello_principaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pannello_principaleLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(pannello_robots, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(pannello_principaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(select_robodromes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_robodromo)
                    .addComponent(jLabel1)
                    .addComponent(select_docks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(pannello_principaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(avvia_allenamento, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_home, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pannello_principale, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pannello_principale, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void select_robodromesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_select_robodromesActionPerformed
        robodrome = (String)select_robodromes.getSelectedItem(); 
    }//GEN-LAST:event_select_robodromesActionPerformed

    private void select_docksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_select_docksActionPerformed
        dock = select_docks.getSelectedIndex() + 1;
    }//GEN-LAST:event_select_docksActionPerformed

    private void robot_bluMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_robot_bluMouseClicked
        update_selected(robot_blu);
    }//GEN-LAST:event_robot_bluMouseClicked

    private void robot_turquoiseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_robot_turquoiseMouseClicked
        update_selected(robot_turquoise);
    }//GEN-LAST:event_robot_turquoiseMouseClicked

    private void robot_violetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_robot_violetMouseClicked
        update_selected(robot_violet);
    }//GEN-LAST:event_robot_violetMouseClicked

    private void robot_orangeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_robot_orangeMouseClicked
        update_selected(robot_orange);
    }//GEN-LAST:event_robot_orangeMouseClicked

    private void robot_greenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_robot_greenMouseClicked
        update_selected(robot_green);
    }//GEN-LAST:event_robot_greenMouseClicked

    private void robot_emeraldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_robot_emeraldMouseClicked
        update_selected(robot_emerald);
    }//GEN-LAST:event_robot_emeraldMouseClicked

    private void robot_redMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_robot_redMouseClicked
        update_selected(robot_red);
    }//GEN-LAST:event_robot_redMouseClicked

    private void robot_yellowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_robot_yellowMouseClicked
        update_selected(robot_yellow);
    }//GEN-LAST:event_robot_yellowMouseClicked

    private void avvia_allenamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avvia_allenamentoActionPerformed
        if (selected != null){
            String temp_name_robot = GestoreProgrammazione.icon_to_key(selected.getIcon().toString());
            this.dispose();
            RobotMarker robot = new RobotMarker(temp_name_robot,temp_name_robot.substring(0, temp_name_robot.lastIndexOf('-')));
            robot.assign("Allenamento", dock);
            new AllenarsiApp("robodromes/"+robodrome+".txt", robot).setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Clicka su uno dei robot per selezionarlo!");
        }        
    }//GEN-LAST:event_avvia_allenamentoActionPerformed

    private void button_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_homeActionPerformed
        this.dispose();
        new RoboGP_Client.Client().setVisible(true);
    }//GEN-LAST:event_button_homeActionPerformed

    private void update_selected(JLabel new_selected){
        if (selected != null)
            selected.setBorder(BorderFactory.createLineBorder(Color.black, 5, true));//cambiare colore al border selezionato e metterlo nuovo al nuovo_selezionato
        new_selected.setBorder(BorderFactory.createLineBorder(Color.green, 5, true));
        selected = new_selected;
        System.out.println("Selezionato: " + GestoreProgrammazione.icon_to_key(new_selected.getIcon().toString()));
    }
    
/**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(setting_allenamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(setting_allenamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(setting_allenamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(setting_allenamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new setting_allenamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton avvia_allenamento;
    private javax.swing.JButton button_home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel label_robodromo;
    private javax.swing.JPanel pannello_principale;
    private javax.swing.JPanel pannello_robots;
    private javax.swing.JLabel robot_blu;
    private javax.swing.JLabel robot_emerald;
    private javax.swing.JLabel robot_green;
    private javax.swing.JLabel robot_orange;
    private javax.swing.JLabel robot_red;
    private javax.swing.JLabel robot_turquoise;
    private javax.swing.JLabel robot_violet;
    private javax.swing.JLabel robot_yellow;
    private javax.swing.JComboBox<String> select_docks;
    private javax.swing.JComboBox<String> select_robodromes;
    // End of variables declaration//GEN-END:variables
}
